# Generated by Django 4.1.3 on 2022-11-17 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_rename_data_criacao_contato_data_de_criacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='Data_de_criacao',
            new_name='Data_de_Criação',
        ),
    ]
