# Generated by Django 4.1.3 on 2022-11-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_rename_data_de_criacao_contato_data_de_criação'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
