# Generated by Django 4.1.3 on 2022-11-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0007_alter_contato_foto_alter_contato_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='foto',
            field=models.ImageField(upload_to='fotos/%Y/%m/%D'),
        ),
    ]
